// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRQ6CQWD5herNJVvb1L3DfFoyGSR6OayA',
    appId: '1:191221685059:web:5c5ffaced26bc26daaadf6',
    messagingSenderId: '191221685059',
    projectId: 'flutter-e-commerce-3fbf5',
    authDomain: 'flutter-e-commerce-3fbf5.firebaseapp.com',
    storageBucket: 'flutter-e-commerce-3fbf5.appspot.com',
    measurementId: 'G-9XP7MZ5NB3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6Ajsio5vG8E0g6Dozn5DsxA_subhKyzc',
    appId: '1:191221685059:android:4ade0acf03bfe636aaadf6',
    messagingSenderId: '191221685059',
    projectId: 'flutter-e-commerce-3fbf5',
    storageBucket: 'flutter-e-commerce-3fbf5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbWWBuKcDt-nCEg9eZNpuQUqb8f9jEvrs',
    appId: '1:191221685059:ios:e77ad9ddf53eb0bcaaadf6',
    messagingSenderId: '191221685059',
    projectId: 'flutter-e-commerce-3fbf5',
    storageBucket: 'flutter-e-commerce-3fbf5.appspot.com',
    iosClientId:
        '191221685059-k55g2l0j2rjl6adknuanmijaqooo4hd2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterEcommerce',
  );
}
